const Action = {

    ADD_EXERCISE:"ADD_EXERCISE",
    REMOVE_EXERCISE:"REMOVE_EXERCISE",
    EDIT_EXERCISE:"EDIT_EXERCISE",
    ADD_BODYPART:"ADD_BODYPART",
    REMOVE_BODYPART:"REMOVE_BODYPART"
}

export default Action;